// Automatically generated by make_default_presets.py

#define PRESET_NAMES { "PRESETS", "Preset 1"}

constexpr char* PRESET_ID_LIST[]{
  "PRESET_FILENAMES", "Preset_1"
};

constexpr wchar_t* PRESET_ID_LIST_W[]{L"WIDE_PRESET_FILENAMES", L"Preset_1"};

constexpr int N_PRESETS = 2;
